SWAGGER-138 add next_day conversion date
CurrencyCloud/currencycloud-swagger pull request #169
Opened 2021-02-09 15:53 UTC by connicov1

## [SWAGGER-138](https://ccycloud.atlassian.net/browse/SWAGGER-138)

## Brief description of what is being done

Added NEW `next_day` conversion date option for ConversionDates endpoint

## NOTE:

Should be merged when [pricing ticket](https://github.com/ccycloud/pricing/pull/475) is merged

2021-02-09 17:47 UTC, jonathancouchman submitted a review, later dismissed

2021-02-11 18:33 UTC, thiagotsai requested changes
Needs to add 'next_day' as a conversion_date_preference option of rates/detailed and conversions/create endpoints

2021-02-11 19:04 UTC, thiagotsai approved these changes

2021-02-12 18:46 UTC, incogneato approved these changes

2021-02-18 14:44 UTC, jonathancouchman approved these changes

2021-02-18 14:44 UTC, merged