New dev centre structure
CurrencyCloud/currencycloud-swagger pull request #230
Opened 2022-10-28 14:37 UTC by maria-thom

2022-10-28 14:50 UTC, jonathancouchman requested changes
@maria-thom I think we need to be careful when refactoring this repository. It is not only the source for the Developer centre. The key file is the reference.yaml swagger definition. This will be used for customers to implement their own clients. 

I think we need a clearer separation of the swagger definition and the developer centre source files. The swagger file is not data, it is a key source file. I think it should be moved to a src/v2/ directory 

In addition, I do not think the response files should be in this repo. They are auto generated and should be in the main developer-centre repo.

Finally, I think the README should be reworded, to explain that the swagger file is the API documentation for the api-v2 etc.

2022-10-28 15:36 UTC, maria-thom commented
> @maria-thom I think we need to be careful when refactoring this repository. It is not only the source for the Developer centre. The key file is the reference.yaml swagger definition. This will be used for customers to implement their own clients.
> 
> I think we need a clearer separation of the swagger definition and the developer centre source files. The swagger file is not data, it is a key source file. I think it should be moved to a src/v2/ directory
> 
> In addition, I do not think the response files should be in this repo. They are auto generated and should be in the main developer-centre repo.
> 
> Finally, I think the README should be reworded, to explain that the swagger file is the API documentation for the api-v2 etc.

@gergelykovacs I'll make the changes suggested by @jonathancouchman here.  We will need to change the pipeline to pick up the swagger spec(s) from the src directory.

2022-11-01 15:25 UTC, jonathancouchman approved these changes

2022-11-04 11:45 UTC, gergelykovacs approved these changes

2022-11-04 11:47 UTC, merged